//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DymShopProject.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.orderproducts = new HashSet<orderproduct>();
        }
    
        public int OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDateStart { get; set; }
        public Nullable<System.DateTime> OrderDateDelivery { get; set; }
        public Nullable<int> OrderPickPoint { get; set; }
        public int OrderBuyer { get; set; }
        public Nullable<int> OrderCode { get; set; }
        public string OrderStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderproduct> orderproducts { get; set; }
        public virtual pickuppoint pickuppoint { get; set; }
        public virtual user user { get; set; }
    }
}
